static const char* const s_default_fragment_shader = "#version 330\n"
"\n"
"uniform sampler2D g_Sampler;\n"
"uniform vec4 g_TintColor;\n"
"\n"
"in vec2 ex_TexCoord;\n"
"out vec4 out_Color;\n"
"\n"
"void main()\n"
"{\n"
"    out_Color = g_TintColor * texture(g_Sampler, ex_TexCoord);\n"
"};\n"
"\n"
;